language: go

go:
- 1.9
- tip

before_install:
- go get github.com/mattn/goveralls
- go get github.com/alecthomas/gometalinter
- go get -u github.com/go-swagger/go-swagger/cmd/swagger

install:
- gometalinter --install

script:
- make test
- goveralls -service=travis-ci
