language: go

go:
- 1.x
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get github.com/alecthomas/gometalinter
- go get -u golang.org/x/vgo

install:
- gometalinter --install

script:
- GO=vgo make test
