
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/gin-contrib/pprof"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/go-openapi/errors"

[[constraint]]
  name = "github.com/go-openapi/runtime"

[[constraint]]
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  name = "github.com/go-openapi/swag"

[[constraint]]
  name = "github.com/go-openapi/validate"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.3"

[[constraint]]
  name = "github.com/zalando/gin-oauth2"
  version = "~1.4.1"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "~2.2.5"
